### ISSUE TITLE
请教下这行代码JQDataClient.instance().get_price(**locals())怎么理解

### ISSUE THREAD

**Issue by silent494529371** [DingTobest/JQdataServiceForVNPY#1]
搞不明白这行代码是如何把数据一行行的取出来的

**Comment by silent494529371** [comment]
请教有办法一次性的下载到主力合约数据吗

**Comment by DingTobest** [comment]
这部分程序是JQData的API，JQData数据我的每日有数量限制，每天100万，用JQData数据量不够，不能一次补齐。你可以考虑一下其他手段补齐这历史数据。这个数据服务主要是做每日更新和短期数据补齐用。
